[GDRIVE]
type = drive
client_id = 408987810634-j5s5bisdlrc9am98cehlv644ei70caku.apps.googleusercontent.com
client_secret = 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
scope = drive
token = {"access_token":"ya29.a0AfB_byD_JNkbx4ND3OkOUX9ju7YxrRyQ7U4tR3InNRppm2a5qEaVby127eQm6GnVquA4w1SZJm0ujdMZXdqdlKMNprb6kmcaQC9n5EHDbZ_imjCPiVdJ7q3fl8V17ciTAsORGc0TAXTNlx3nu7CrQ3eFCiB-rX7lUilpMNUaCgYKASgSARASFQHGX2MiLAHOlIVgRrJiLezOasbCmQ0174","token_type":"Bearer","refresh_token":"1//03m_aO4nv6CctCgYIARAAGAMSNwF-L9IrxW0XibORQQ8It1_S9I1bTNRC1x1ZvOO8HYHhW4UU4IDf8D3NEVq5BJ6bV-M-vW4CbKA","expiry":"2024-01-02T15:08:55.01959666+03:00"}
team_drive = 

